theme = "catppuccin_macchiato" 

[editor]
true-color = true
color-modes = true
line-number = "relative"
mouse = false
trim-trailing-whitespace = true
bufferline = "always"
end-of-line-diagnostics = "hint"
clipboard-provider = "pasteboard"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
auto-signature-help = false

[editor.indent-guides]
render = true
character = "|"
skip-level = 0

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up= ["extend_to_line_bounds", "delete_selection", "move_line_up","paste_before"]

[keys.insert]
C-h = ["move_prev_word_end", "collapse_selection"]
C-l = ["move_next_word_end", "collapse_selection"]

[editor.cursor-shape]
insert = "bar"
